// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEdialogsData : IGDEData
    {
        private static string boolfieldKey = "boolfield";
		private bool _boolfield;
        public bool boolfield
        {
            get { return _boolfield; }
            set {
                if (_boolfield != value)
                {
                    _boolfield = value;
                    GDEDataManager.SetBool(_key+"_"+boolfieldKey, _boolfield);
                }
            }
        }

        private static string floatfieldKey = "floatfield";
		private float _floatfield;
        public float floatfield
        {
            get { return _floatfield; }
            set {
                if (_floatfield != value)
                {
                    _floatfield = value;
                    GDEDataManager.SetFloat(_key+"_"+floatfieldKey, _floatfield);
                }
            }
        }

        public GDEdialogsData()
		{
			_key = string.Empty;
		}

		public GDEdialogsData(string key)
		{
			_key = key;
		}
		
        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetBool(boolfieldKey, out _boolfield);
                dict.TryGetFloat(floatfieldKey, out _floatfield);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _boolfield = GDEDataManager.GetBool(_key+"_"+boolfieldKey, _boolfield);
            _floatfield = GDEDataManager.GetFloat(_key+"_"+floatfieldKey, _floatfield);
         }

        public void Reset_boolfield()
        {
            GDEDataManager.ResetToDefault(_key, boolfieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetBool(boolfieldKey, out _boolfield);
        }

        public void Reset_floatfield()
        {
            GDEDataManager.ResetToDefault(_key, floatfieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(floatfieldKey, out _floatfield);
        }

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, boolfieldKey);
            GDEDataManager.ResetToDefault(_key, floatfieldKey);


            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
