// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string events_SpecialEvent = "SpecialEvent";
        public static string events_VerySpecialEvent = "VerySpecialEvent";
        public static string events_GoogleItem = "GoogleItem";
    }
}
